// Generated by https://quicktype.io

import { CitaMedicaViewModel } from './CitaMedicaViewModel';

export interface CrearCitaMedica {
  citaMedica: CitaMedicaViewModel;
  pacienteId: string;
  medicoId: string;
}
