// Generated by https://quicktype.io

import { CitaMedicaViewModel } from './CitaMedicaViewModel';

export interface CrearCitaMedica {
  citaMedica: CrearCita;
  pacienteId: string;
  medicoId: string;
}
interface CrearCita {
  sintomas: string;
  fecha: Date;
  hora: Date;
}
