// Generated by https://quicktype.io

import { CitaMedicaViewModel } from './CitaMedicaViewModel';

export interface CrearCitaMedica {
  citaMedica: CrearCita;
  pacienteId: string;
  medicoId: string;
}
export interface CrearCita {
  sintomas: string;
  fecha: string;
  hora: string;
}
