// Generated by https://quicktype.io

import { HistorialMedico } from 'src/app/models';

export interface HistorialMedicoResponse {
  isSuccess: boolean;
  message: string;
  result: HistorialMedico;
}
