// Generated by https://quicktype.io

import { HistorialMedico } from 'src/app/models';

export interface HistorialesMedicosResponse {
  isSuccess: boolean;
  message: string;
  result: HistorialMedico[];
}
