// Generated by https://quicktype.io

import { Pacientes } from './pacientes.interface';

export interface HistorialPacienteResponse {
  isSuccess: boolean;
  message: string;
  result: HistorialPaciente[];
}

export interface HistorialPaciente {
  id: string;
  pacienteId: string;
  medicoId: string;
  citaMedicaId: string;
  citaMedica: null;
}
