// Generated by https://quicktype.io
export interface HistorialPacienteResponse {
  isSuccess: boolean;
  message: string;
  result: HistorialMedico[];
}

export interface HistorialMedico {
  id: string;
  pacienteId: string;
  paciente: Paciente;
  medicoId: string;
  medico: Medico;
  citaMedicaId: string;
  citaMedica: CitaMedica;
}

export interface CitaMedica {
  id: string;
  fecha: Date;
  hora: string;
  sintomas: string;
}

export interface Medico {
  id: string;
  nombre: string;
  email: string;
  telefono: string;
  especialidad: string;
}

export interface Paciente {
  id: string;
  nombre: string;
  email: string;
}
