import { HistorialMedico } from 'src/app/models';

// Generated by https://quicktype.io
export interface HistorialPacienteResponse {
  isSuccess: boolean;
  message: string;
  result: HistorialMedico[];
}
