// Generated by https://quicktype.io

export interface PacienteResponse {
  isSuccess: boolean;
  message: string;
  result: Paciente;
}

export interface Paciente {
  id: string;
  nombre: string;
  email: string;
}
