// Generated by https://quicktype.io

export interface PacientesResponse {
  isSuccess: boolean;
  message: string;
  result: Pacientes[];
}

export interface Pacientes {
  id: string;
  nombre: string;
  email: string;
}
