// Generated by https://quicktype.io

import { CitaMedicaViewModel } from '../models/CitaMedicaViewModel';

export interface CrearCitaMedicaResponse {
  message: string;
  data: Data;
}
interface Data {
  citaMedica: CitaMedicaViewModel;
  pacienteId: string;
  medicoId: string;
}
